### PR TITLE
add Linear elasticity

### PR DESCRIPTION
**Pull request by npaster**

### CODE REVIEW

**Comment by npaster** [comment]
update linear elasticity for revolution branch

**Comment by datafl4sh** [comment]
Hi Nicolas,Thank you for the PR. Actually, I’m missing the gmsh_tools sources, maybe you forgot to add them to the repo.Thanks,-mc.Il giorno 19 mar 2018, alle ore 13:47, npaster <notifications@github.com> ha scritto:update linear elasticity for revolution branch—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by npaster** [comment]
Hi Matteo,

I only added the CmakeFile file to ensure the compilation. I modified the .gitmodule to add the link to the repo where are the sources for gmsh_tools.

I can directly add them into the repo if you prefer?

Best,

Nicolas

**Comment by datafl4sh** [comment]
> Il giorno 19 mar 2018, alle ore 14:50, npaster <notifications@github.com> ha scritto:
> 
> Hi Matteo,
> 
> I only added the CmakeFile file to ensure the compilation. I modified the .gitmodule to add the link to the repo where are the sources for gmsh_tools.
> 
> I can directly add them into the repo if you prefer?

My mistake. Thanks :)

-mc.

**Pull request merged**
